import 'package:uidesign/constant/Image.dart';
import 'package:uidesign/constant/String.dart';
List categoryname = [
    (Stringtext.category1),
    (Stringtext.category2),
    (Stringtext.category3),
    (Stringtext.category4),
    (Stringtext.category5),
    (Stringtext.category6),
    (Stringtext.category7),
    (Stringtext.category8),
    (Stringtext.category9),
    (Stringtext.category10),
    (Stringtext.category11),
    (Stringtext.category12),
    (Stringtext.category13),
    (Stringtext.category14),
    (Stringtext.category15),
    (Stringtext.category6),
  ];
  List<String> categoryimage = [
    (LookPriorImage.category1),
    (LookPriorImage.category2),
    (LookPriorImage.category3),
    (LookPriorImage.category4),
    (LookPriorImage.category5),
    (LookPriorImage.category6),
    (LookPriorImage.category7),
    (LookPriorImage.category8),
    (LookPriorImage.category9),
    (LookPriorImage.category10),
    (LookPriorImage.category11),
    (LookPriorImage.category12),
    (LookPriorImage.category13),
    (LookPriorImage.category14),
    (LookPriorImage.category15),
    (LookPriorImage.category6),
  ];

  List<String> subcategory = [
    (Stringtext.subcate1),
    (Stringtext.subcate2),
    (Stringtext.subcate3),
    (Stringtext.subcate4),
    (Stringtext.subcate5),
    (Stringtext.subcate6),
    (Stringtext.subcate7),
    (Stringtext.subcate8),
    (Stringtext.subcate9),
    (Stringtext.subcate10),
    (Stringtext.subcate11),
  ];
